services:
  cros_db:
    container_name: cros_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
      MYSQL_DATABASE: teste_cros_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
